### PR TITLE
Issue 105 race conditions

### LINKED ISSUE #105: Data races in extract and export for short rac-files
Two modules; extractors and exports have data races in their test cases, as well as the application, when using small enough rac-files. It is probably the setup of the tests that makes the data race happen, since it is not visible in the application.
```
$ go test -race ./...
ok      github.com/innosat-mats/rac-extract-payload/cmd/rac     0.033s
ok      github.com/innosat-mats/rac-extract-payload/internal/aez        0.248s
ok      github.com/innosat-mats/rac-extract-payload/internal/awstools   0.041s
ok      github.com/innosat-mats/rac-extract-payload/internal/ccsds      0.026s
ok      github.com/innosat-mats/rac-extract-payload/internal/common     0.034s
ok      github.com/innosat-mats/rac-extract-payload/internal/decodejpeg 0.438s
2020/05/25 10:32:42 here be dragons
==================
WARNING: DATA RACE
Read at 0x00c0002a53f0 by goroutine 19:
  github.com/innosat-mats/rac-extract-payload/internal/exports.TestAWSS3CallbackFactory.func1.1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer_test.go:179 +0x11d
  github.com/innosat-mats/rac-extract-payload/internal/exports.AWSS3CallbackFactory.func1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer.go:61 +0x11b

Previous write at 0x00c0002a53f0 by goroutine 18:
  github.com/innosat-mats/rac-extract-payload/internal/exports.TestAWSS3CallbackFactory.func1.1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer_test.go:195 +0x28d
  github.com/innosat-mats/rac-extract-payload/internal/awstools.(*Timeseries).Close()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/awstools/timeseries.go:30 +0x1b1
  github.com/innosat-mats/rac-extract-payload/internal/timeseries.(*CSV).Close()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/timeseries/csv.go:47 +0xe2
  github.com/innosat-mats/rac-extract-payload/internal/timeseries.(*CSVCollection).CloseAll()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/timeseries/csv_collection.go:60 +0x152
  github.com/innosat-mats/rac-extract-payload/internal/exports.AWSS3CallbackFactory.func3()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer.go:107 +0x4a
  github.com/innosat-mats/rac-extract-payload/internal/exports.TestAWSS3CallbackFactory.func1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer_test.go:241 +0x3db
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:991 +0x1eb

Goroutine 19 (running) created at:
  github.com/innosat-mats/rac-extract-payload/internal/exports.AWSS3CallbackFactory()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer.go:56 +0x642
  github.com/innosat-mats/rac-extract-payload/internal/exports.TestAWSS3CallbackFactory.func1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer_test.go:229 +0x2bf
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:991 +0x1eb

Goroutine 18 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1042 +0x660
  github.com/innosat-mats/rac-extract-payload/internal/exports.TestAWSS3CallbackFactory()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/exports/aws_s3_writer_test.go:173 +0x1130
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:991 +0x1eb
==================
--- FAIL: TestAWSS3CallbackFactory (0.05s)
    --- FAIL: TestAWSS3CallbackFactory/Uploads_everything (0.03s)
        testing.go:906: race detected during execution of test
    testing.go:906: race detected during execution of test
FAIL
FAIL    github.com/innosat-mats/rac-extract-payload/internal/exports    0.171s
==================
WARNING: DATA RACE
Write at 0x00c0000a0528 by main goroutine:
  internal/race.Write()
      /usr/local/go/src/internal/race/race.go:41 +0x114
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/sync/waitgroup.go:128 +0x115
  github.com/innosat-mats/rac-extract-payload/internal/extractors.ExtractData()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/extractors/extract_data.go:49 +0x447
  github.com/innosat-mats/rac-extract-payload/internal/extractors.Example()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/extractors/extract_data_test.go:100 +0x3a4
  testing.runExample()
      /usr/local/go/src/testing/run_example.go:62 +0x274
  testing.runExamples()
      /usr/local/go/src/testing/example.go:44 +0x211
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1200 +0x3b3
  main.main()
      _testmain.go:64 +0x223

Previous read at 0x00c0000a0528 by goroutine 28:
  internal/race.Read()
      /usr/local/go/src/internal/race/race.go:37 +0x1e8
  sync.(*WaitGroup).Add()
      /usr/local/go/src/sync/waitgroup.go:71 +0x1fb
  github.com/innosat-mats/rac-extract-payload/internal/extractors.ExtractData.func1()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/extractors/extract_data.go:27 +0x5c

Goroutine 28 (running) created at:
  github.com/innosat-mats/rac-extract-payload/internal/extractors.ExtractData()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/extractors/extract_data.go:26 +0x1e8
  github.com/innosat-mats/rac-extract-payload/internal/extractors.Example()
      /home/joakim/go/src/github.com/innosat-mats/rac-extract-payload/internal/extractors/extract_data_test.go:100 +0x3a4
  testing.runExample()
      /usr/local/go/src/testing/run_example.go:62 +0x274
  testing.runExamples()
      /usr/local/go/src/testing/example.go:44 +0x211
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1200 +0x3b3
  main.main()
      _testmain.go:64 +0x223
==================
FAIL
FAIL    github.com/innosat-mats/rac-extract-payload/internal/extractors 0.048s
ok      github.com/innosat-mats/rac-extract-payload/internal/innosat    0.036s
ok      github.com/innosat-mats/rac-extract-payload/internal/ramses     0.033s
ok      github.com/innosat-mats/rac-extract-payload/internal/timeseries 0.085s
FAIL
```

Original bug description:

It seems to be able to happen, but not always and I have no idea why.

Could it be some hidden timing flaw within the core logic of our control flow?

```
 Test
5s
##[error]Process completed with exit code 2.
ok  	github.com/innosat-mats/rac-extract-payload/internal/awstools	0.007s
ok  	github.com/innosat-mats/rac-extract-payload/internal/ccsds	0.004s
ok  	github.com/innosat-mats/rac-extract-payload/internal/common	0.007s
ok  	github.com/innosat-mats/rac-extract-payload/internal/decodejpeg	0.062s
ok  	github.com/innosat-mats/rac-extract-payload/internal/exports	0.011s
--- FAIL: Example (0.00s)
got:

want:
got stop packet without a start packet (Set1)
 STAT <nil>
  checksum bad 62691
 STAT <nil>
  checksum bad 32488
  got stop packet without a start packet (Set2)
 STAT <nil>
  checksum bad 62691
 STAT <nil>
  checksum bad 32488
FAIL
FAIL	github.com/innosat-mats/rac-extract-payload/internal/extractors	0.005s
ok  	github.com/innosat-mats/rac-extract-payload/internal/innosat	0.003s
ok  	github.com/innosat-mats/rac-extract-payload/internal/ramses	0.010s
ok  	github.com/innosat-mats/rac-extract-payload/internal/timeseries	0.007s
FAIL
##[error]Makefile:20: recipe for target 'test' failed
make: *** [test] Error 1
##[error]Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by skymandr**
Fix race conditions. 

* Fix for the first race condition (extractors) implemented by moving `wg.Add()` to outside `go func`. 

* Fix for race condition when writing PNGs to AWS implemented by simply removing the parallelization of the ABOUT file. This seems a little crude and maybe there is a better solution - separate wait groups perhaps? On the other hand, since the about file is small, perhaps this is good enough?

* Fix second race condition for AWS by changing order in `teardown` of factory.

* This PR also adds the `-race` flag to the `test` target in the `Makefile`. Hopefully this won't be annoying.

Resolves #105

### CODE REVIEW

File: internal/exports/aws_s3_writer.go [hunk 1]
```diff
@@ -52,15 +52,11 @@ func AWSS3CallbackFactory(
...
-		go func() {
-			key := fmt.Sprintf("ABOUT%v", filepath.Ext(awsDescriptionPath))
-			if project != "" {
-				key = fmt.Sprintf("%v/%v", project, key)
-			}
-			upload(uploader, key, awsDescription)
-			wg.Done()
-		}()
+		key := fmt.Sprintf("ABOUT%v", filepath.Ext(awsDescriptionPath))
+		if project != "" {
```
Comment (local-minimum) [inline internal/exports/aws_s3_writer.go:56]: would it not have worked with `defer wg.Done()` inside the go-routine instead? But sure it's probably small and wont matter much.

File: internal/exports/aws_s3_writer_test.go [hunk 2]
```diff
@@ -263,6 +263,7 @@ func TestAWSS3CallbackFactory(t *testing.T) {
 			for _, record := range tt.records {
 				callback(record)
 			}
+			wg.Wait()
```
Comment (local-minimum) [inline internal/exports/aws_s3_writer_test.go]: this seems wrong in that it doesn't follow the logic in the implementation. the wait should be part of the teardown function.

Comment (local-minimum) [reply internal/exports/aws_s3_writer_test.go]: or it should never be part of any of the teardown functions, I suppose.

File: internal/exports/aws_s3_writer.go (hunk 1 above)
Comment (skymandr) [reply internal/exports/aws_s3_writer.go:56]: No, that was not enough.

File: internal/exports/aws_s3_writer_test.go (hunk 2 above)
Comment (skymandr) [reply internal/exports/aws_s3_writer_test.go]: Without it, the test causes a race, which I so far haven't been able to reproduce outside the test.

File: internal/exports/aws_s3_writer.go (hunk 1 above)
Comment (skymandr) [reply internal/exports/aws_s3_writer.go:56]: Do you have any other suggestions?

File: internal/exports/aws_s3_writer_test.go (hunk 2 above)
Comment (skymandr) [reply internal/exports/aws_s3_writer_test.go]: I've pushed a new solution, but I'm not sure of the broader implications of the change...

File: internal/exports/aws_s3_writer.go (hunk 1 above)
Comment (local-minimum) [reply internal/exports/aws_s3_writer.go:56]: sorry no, but it's fine to have it sequentially upload it, I think.

File: internal/exports/aws_s3_writer_test.go (hunk 2 above)
Comment (local-minimum) [reply internal/exports/aws_s3_writer_test.go]: do we fail to pass the waitgroup by reference somewhere? because if it requires you to put it there on 266, then it is a problem in the actual code, not the test itself.

Comment (skymandr) [reply internal/exports/aws_s3_writer_test.go]: I removed it from 266 and made a change in the `teardown` instead. Not sure that's better, since I don't quite understand the implications...

Comment (skymandr) [reply internal/exports/aws_s3_writer_test.go]: (And yes, I suspect the problem is in the actual code, though at the moment I can't tell you why I suspect this. `Guru meditation error 0x2A: Not enough tea.`)

File: internal/exports/aws_s3_writer.go (hunk 1 above)
Comment (skymandr) [reply internal/exports/aws_s3_writer.go:56]: Cool. I'll see what @joakimmoller thinks before resolving this.

**Review by joakimmoller — APPROVED** [review]
Looks good to me, I've run a trace on it - it looks alright.
